RDKBCMF-248 fix emu-b build failure on wifi easyconnect (44686) import
build failure:
| In file included from
../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/source-pc/TR-181/sbapi/cosa_wifi_apis.c:73:0:
|
../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:146:5:
error: unknown type name 'COSA_DML_WIFI_DPP_CFG'
|      COSA_DML_WIFI_DPP_CFG        DPP;

emu-b source-pc code needs to handle struct changes on this import

Change-Id: I6b09ea7447eb7d1f63754e4f6a1502d84dd44c75