REFPLTB-1701 RPi Broadband build failures when WifiHAL3 is enabled
Build errors in RPi BB builds when WifiHAL3 is enabled,
in the ccsp-wifi-agent component:
cosa_wifi_apis.c:9750:28: error: 'apIndex' undeclared (first use in this function)
cosa_wifi_apis.c:9751:28: error: 'index' undeclared (first use in this function)
cosa_wifi_apis.c:9752:28: error: 'idx' undeclared (first use in this function)
-Werror=unused-but-set-variable
-Werror=sign-compare

Change-Id: I45900b210c070431536c50284f4e14517f2ca270