RDKCOM-1290: Add COSA_DML_WIFI_GASCFG and COSA_DML_WIFI_GASSTATS defines for...
These typedefs fix build errors:
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:255:9: error: unknown type name 'COSA_DML_WIFI_GASCFG'
|          COSA_DML_WIFI_GASCFG            GASCfg[1];                  |          ^
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:262:2: note: in expansion of macro 'COSA_DATAMODEL_WIFI_CLASS_CONTENT'
|   COSA_DATAMODEL_WIFI_CLASS_CONTENT
|   ^
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:256:9: error: unknown type name 'COSA_DML_WIFI_GASSTATS'
|          COSA_DML_WIFI_GASSTATS          GASStats[1];                  |          ^
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:262:2: note: in expansion of macro 'COSA_DATAMODEL_WIFI_CLASS_CONTENT'
|   COSA_DATAMODEL_WIFI_CLASS_CONTENT
|   ^

Reason for change: Add COSA_DML_WIFI_GASCFG and COSA_DML_WIFI_GASSTATS defines for...
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 02cd6cc30ffefc390522239f8bbfd6758fa4558b)
Change-Id: Id94802e3e7a16aae365fef2c090f145c2aa9d12e