RDKCOM-2456 RDKBCMF-281 CcspWifiAgent build failure
Fix CcspWifiAgent build failure as a result of CcspWifiAgent/62688:
CcspWifiAgent/source/TR-181/sbapi/cosa_wifi_apis.c:23283:17: error: 'rc' undeclared (first use in this function)
23283 |                 rc = strcpy_s(hosts.host[j].AssociatedDevice,sizeof(hosts.host[j].AssociatedDevice),assoc_device);
      |                 ^~

Reason for change: RDKBCMF-281 CcspWifiAgent build failure
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

Change-Id: I0dd46860ae9a417a1407b13de3f358fc08d7f5de
(cherry picked from commit c4ab04078d054a77d42c6e531eb61c0826913ff7)