RDKCOM-1356 RDKBCMF-247 Add missing defintions in emulator source
The definitions missing from emulator source was moved from general
to platform specific header files in CcspWifiAgent/43842, causing
build errors:
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:183:2: error: unknown type name 'PCOSA_DML_WIFI_HARVESTER'
|   PCOSA_DML_WIFI_HARVESTER  pHarvester;
|   ^
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:390:9: error: unknown type name 'PCOSA_DML_WIFI_ACTIVE_MSMT_STEP_CFG'
|          PCOSA_DML_WIFI_ACTIVE_MSMT_STEP_CFG pStepCfg,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This change add the missing definitions back to emulator specific header file, copied from the original change.

Reason for change: RDKBCMF-247 Add missing defintions in emulator source
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 1bb6bdc1f400b954c8231b5df6901414515c88fa)
Change-Id: If81f0d480ae3e74eed99258b922477b2e1cc25c6