RDKCOM-1376 RDKBCMF-248 fix emu-b build failure on wifi easyconnect (44686)...
build failure:
| In file included from
../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/source-pc/TR-181/sbapi/cosa_wifi_apis.c:73:0:
|
../../../../../../../../../../rdkb/components/opensource/ccsp/CcspWifiAgent/include/TR-181/ml/cosa_wifi_internal.h:146:5:
error: unknown type name 'COSA_DML_WIFI_DPP_CFG'
|      COSA_DML_WIFI_DPP_CFG        DPP;
emu-b source-pc code needs to handle struct changes on this import

Reason for change: RDKBCMF-248 fix emu-b build failure on wifi easyconnect (44686)...
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>
(cherry picked from commit c7d1e3aca7df02f098cfe6b6b9c180e1aac8ad3e)
Change-Id: Ib365c03f2cba6f3aeb529c66ba73aae3f90e53bc