RDKB-25152: Add Device.WiFi.X_RDKCENTRAL-COM_Report.WifiClient. data model
Reason for change: Instantanous measurements for chosen client
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

RDKB-25152: Add all AC for WifiClient data model

Reason for change: Instantanous measurements for chosen client
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

Change-Id: Ia65b91aeda9827a7b62835f75bec5b183122ac7e

RDKB-25152: Add Device.WiFi.X_RDKCENTRAL-COM_Report.WifiClient.Default. data model

Reason for change: Instantanous measurements for chosen client
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

RDKB-25152: Update cosa_wifi_api.c to latest 1910

Reason for change: Instantanous measurements for chosen client
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

Change-Id: Ia0a75eb4bcbbc530a76ecb6a2ced8044e8904892

RDKB-25220: Create new avro schema for single client InstantWifi report

Reason for change: To define new schema for single client instantaneous measurement without array and to add any additional data parameters which needs to be send in the real time report.
Test Procedure: Check /tmp/WifiMon logs and confirm no avro errors. Wifi single client reports are send successfully to cloud.
Risks: Low
Signed-off-by: sadhyama_vengilat2@cable.comcast.com
Change-Id: Ia0a75eb4bcbbc530a76ecb6a2ced8044e8904892

RDKB-25152: Wifi Agent not coming up due to undefined symbol

Reason for change: Adding print_hex_dump and getTimeOffsetFromUtc
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

Change-Id: I473bddf5f762de50febd81a334f01077e3f09b5f

RDKB-25982: WifiAgent crash when wifi single client report is enabled

Reason for change: To check single client report issue in CBR
Test Procedure: Check /tmp/WifiMon logs and confirm no avro errors. Wifi single client reports are send successfully to cloud.
Risks: Low
Signed-off-by: sadhyama_vengilat2@cable.comcast.com

Change-Id: I4e891cae26f1d4d3cfecd5131bdcb4a15be68f73

RDKB-26130: Enable hal API for XB6

Reason for change: Instantanous measurements for chosen client
Test Procedure: Build and install image in AXB3
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

Change-Id: I7a64385a7ff146925377ce8e22b5c657b5719cd9

SKYH4-2095 :  RSSI value are displaying as empty for the older wifi client.

Reason for change:
Issue caused due to RDKB-24606 US changes.
https://gerrit.teamccp.com/#/q/topic:INSTMSMT_PH1-1911+(status:open+OR+status:merged)
Getting below error during Device.WiFi.AccessPoint.<X>.AssociatedDevice.<X>.
====
root@skyhub4:~# 191204-16:59:37.272245 [mod=WIFI, lvl=WARN] [tid=17269] updateBootLogTime-16469 LnF SSID 6:Disabled 7:Disabled 10:Disabled 11:Disabled
191204-16:59:37.391403 [mod=WIFI, lvl=WARN] [tid=4838] Failed to get parameter value of 'InstantMeasurementsEnable'.
===

Test Procedure:
1.  CcspWiFiAgent should work without any regression
2.  RSSI value should display for all the WiFi connected client in GUi page
3. Below bulk query should display all the values properly,dmcli eRT getv Device.WiFi.AccessPoint.<Index>.AssociatedDevice.

Risks: Low

Change-Id: Ie9ab4a5019a6aba1399b304face6c36a9e18a729
Signed-off-by: Lakshminarayanan Shenbagaraj <lakshminarayanan_shenbagaraj@comcast.com>

RDKB-26134: Modify tx, rx packets in WifiSingleClientReport as per client

Reason for change: To interchange tx, rx packets as all values in the
wifi report should be from client perspective i.e. client transmitted
(AP received from hal api) and client received (AP sent from hal api).
Test Procedure: Check and confirm wifi hal api output and odp report
are correct as cli_PacketsReceived is tx_packets and cli_PacketsSent is rx_packets.
Risks: Low
Signed-off-by: sadhyama_vengilat2@cable.comcast.com

Change-Id: Ic139ef8becd26314add5666740231a604cdc765f

TCXB7-1575 : Undefined reference to hal API

Reason for change: Add platform specific check
Test Procedure: Build and install image in XB7
Risks: None
Signed-off-by: sipra_samantaray@comcast.com

Change-Id: Idb36d9dc1a63e537459ddfd95a95de16ddf97ced

RDKB-26220 : To fix wifi single client report stuck issue

Reason for change: To resolve stack corruption which is leading
to wifi single client report stuck issue
Test Procedure: Test RDKB-24606 Wifi Single client reports
Risks: None
Signed-off-by: shilpa_seshadri@cable.comcast.com

Change-Id: If215a9409a12319617796141b4523b9e74fac71d

RDKB-26297 : To fix Noisefloor in wifi single client report

Reason for change: To fix the AP index check such that correct
Noisefloor is added in the wifi single client report
Test Procedure: Test RDKB-24606 Wifi Single client reports
Risks: None
Signed-off-by: shilpa_seshadri@cable.comcast.com

Change-Id: I767f0aafb70afa6ab223677b2a591c21b7ca5a8a