RDKCOM-3110: REFPLTB-1701 RPi Broadband build failures when WifiHAL3 is enabled
Build errors in RPi BB builds when WifiHAL3 is enabled,
in the ccsp-wifi-agent component:
cosa_wifi_apis.c:9750:28: error: 'apIndex' undeclared (first use in this function)
cosa_wifi_apis.c:9751:28: error: 'index' undeclared (first use in this function)
cosa_wifi_apis.c:9752:28: error: 'idx' undeclared (first use in this function)
-Werror=unused-but-set-variable
-Werror=sign-compare

Reason for change: REFPLTB-1701 RPi Broadband build failures when WifiHAL3 is enabled
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>
(cherry picked from commit 60bd9bf3c3fe6024903b93480f404617c87a528b)
Change-Id: I0f6b7567c2cccc535b0d37e1f810b2d6cc9e6e25